version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dejavu-postgres
    environment:
      POSTGRES_USER: dejavu
      POSTGRES_PASSWORD: dejavu_secret
      POSTGRES_DB: dejavu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dejavu"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dejavu

  redis:
    image: redis:7-alpine
    container_name: dejavu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - dejavu

  nats:
    image: nats:latest
    container_name: dejavu-nats
    command: "-js"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - dejavu

  minio:
    image: minio/minio:latest
    container_name: dejavu-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - dejavu

  adminer:
    image: adminer:latest
    container_name: dejavu-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - dejavu

networks:
  dejavu:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  nats_data:
  minio_data:

